name: in_app_purchaser
description: "A new Flutter project."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/in_app_purchaser.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  adjust_sdk: ^4.38.1
  facebook_app_events: ^0.19.4


  adapty_flutter: ^2.10.2
  purchases_flutter: ^6.30.2
  qonversion_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0