name: in_app_purchaser
description: "It simplifies the integration of in-app purchase services, handles subscription lifecycle events, provides revenue analytics, and ensures a smooth user experience across iOS and Android."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/in_app_purchaser.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  adjust_sdk: ^5.0.3
  facebook_app_events: ^0.19.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0