name: in_app_purchaser_delegate
description: "Manages subscription lifecycle events, purchase validation, and user entitlements for All InAppPurchase services, ensuring accurate revenue tracking and analytics."
version: 1.0.1
repository: https://github.com/Mohiuddin655-PUB/in_app_purchaser.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0